/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as TroubleshootingRouteImport } from './routes/troubleshooting'
import { Route as TicketsRouteImport } from './routes/tickets'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as BackupsRouteImport } from './routes/backups'
import { Route as AssetsRouteImport } from './routes/assets'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TicketsRouteImport } from './routes/tickets.'
import { Route as AssetsRouteImport } from './routes/assets.'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const TroubleshootingRoute = TroubleshootingRouteImport.update({
  id: '/troubleshooting',
  path: '/troubleshooting',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsRoute = TicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const BackupsRoute = BackupsRouteImport.update({
  id: '/backups',
  path: '/backups',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsRoute = AssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsRoute = TicketsRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TicketsRoute,
} as any)
const AssetsRoute = AssetsRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AssetsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assets': typeof AssetsRouteWithChildren
  '/backups': typeof BackupsRoute
  '/knowledge': typeof KnowledgeRoute
  '/tickets': typeof TicketsRouteWithChildren
  '/troubleshooting': typeof TroubleshootingRoute
  '/users': typeof UsersRoute
  '/assets/': typeof AssetsRoute
  '/tickets/': typeof TicketsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/backups': typeof BackupsRoute
  '/knowledge': typeof KnowledgeRoute
  '/troubleshooting': typeof TroubleshootingRoute
  '/users': typeof UsersRoute
  '/assets': typeof AssetsRoute
  '/tickets': typeof TicketsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assets': typeof AssetsRouteWithChildren
  '/backups': typeof BackupsRoute
  '/knowledge': typeof KnowledgeRoute
  '/tickets': typeof TicketsRouteWithChildren
  '/troubleshooting': typeof TroubleshootingRoute
  '/users': typeof UsersRoute
  '/assets/': typeof AssetsRoute
  '/tickets/': typeof TicketsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assets'
    | '/backups'
    | '/knowledge'
    | '/tickets'
    | '/troubleshooting'
    | '/users'
    | '/assets/'
    | '/tickets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/backups'
    | '/knowledge'
    | '/troubleshooting'
    | '/users'
    | '/assets'
    | '/tickets'
  id:
    | '__root__'
    | '/'
    | '/assets'
    | '/backups'
    | '/knowledge'
    | '/tickets'
    | '/troubleshooting'
    | '/users'
    | '/assets/'
    | '/tickets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssetsRoute: typeof AssetsRouteWithChildren
  BackupsRoute: typeof BackupsRoute
  KnowledgeRoute: typeof KnowledgeRoute
  TicketsRoute: typeof TicketsRouteWithChildren
  TroubleshootingRoute: typeof TroubleshootingRoute
  UsersRoute: typeof UsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/troubleshooting': {
      id: '/troubleshooting'
      path: '/troubleshooting'
      fullPath: '/troubleshooting'
      preLoaderRoute: typeof TroubleshootingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets': {
      id: '/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof TicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backups': {
      id: '/backups'
      path: '/backups'
      fullPath: '/backups'
      preLoaderRoute: typeof BackupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets': {
      id: '/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets/': {
      id: '/tickets/'
      path: '/'
      fullPath: '/tickets/'
      preLoaderRoute: typeof TicketsRouteImport
      parentRoute: typeof TicketsRoute
    }
    '/assets/': {
      id: '/assets/'
      path: '/'
      fullPath: '/assets/'
      preLoaderRoute: typeof AssetsRouteImport
      parentRoute: typeof AssetsRoute
    }
  }
}

interface AssetsRouteChildren {
  AssetsRoute: typeof AssetsRoute
}

const AssetsRouteChildren: AssetsRouteChildren = {
  AssetsRoute: AssetsRoute,
}

const AssetsRouteWithChildren =
  AssetsRoute._addFileChildren(AssetsRouteChildren)

interface TicketsRouteChildren {
  TicketsRoute: typeof TicketsRoute
}

const TicketsRouteChildren: TicketsRouteChildren = {
  TicketsRoute: TicketsRoute,
}

const TicketsRouteWithChildren =
  TicketsRoute._addFileChildren(TicketsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssetsRoute: AssetsRouteWithChildren,
  BackupsRoute: BackupsRoute,
  KnowledgeRoute: KnowledgeRoute,
  TicketsRoute: TicketsRouteWithChildren,
  TroubleshootingRoute: TroubleshootingRoute,
  UsersRoute: UsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
